export const CRYPTO_CATEGORIES = [
  "All Coins",
  "Solana Ecosystem",
  "Stablecoins",
  "Meme Token",
  "Layer 1",
  "Smart Contract Platform",
  "DeFi",
  "Fantom Ecosystem",
  "DragonFly Capital Portfolio",
  "Move VM",
  "Fabric Ventures Portfolio",
  "BoostVC Portfolio",
  "Arrington XRP Capital Portfolio",
  "Analytics",
  "TRON Ecosystem",
  "Filesharing",
  "DePIN",
  "Four Meme Ecosystem",
  "Loyalty",
  "DeFiance Capital Portfolio",
  "Hybrid token standard",
  "HECO Ecosystem",
  "Identity",
  "Animoca Brands Portfolio",
  "Binance Smart Chain",
  "Celo Ecosystem",
  "Music",
  "Lending Borrowing",
  "Oracles",
  "Seedify",
  "Privacy",
  "Fenbushi Capital Portfolio",
  "DEX",
  "Parallel EVM",
  "Polkastarter",
  "Standard Crypto Portfolio",
  "MultiversX Ecosystem",
  "Interoperability",
  "Gaming Guild",
  "Mobile Mining",
  "EigenLayer Ecosystem",
  "DAO",
  "Cat-Themed",
  "Inscriptions",
  "IoT",
  "Terra Ecosystem",
  "Arbitrum Ecosystem",
  "Internet Computer Ecosystem",
  "eGirl Capital Portfolio",
  "Generative AI",
  "Bitcoin Ecosystem",
  "Bittensor Ecosystem",
  "Osmosis Ecosystem",
  "Sonic Ecosystem",
  "YZi Labs Portfolio",
  "TokenFi Launchpad",
  "Olympus Pro Ecosystem",
  "CMS Holdings Portfolio",
  "BTCfi",
  "Tokenized Assets",
  "Play To Earn",
  "Polygon Ecosystem",
  "Oasis Ecosystem",
  "Injective Ecosystem",
  "Near Protocol Ecosystem",
  "Binance Launchpad",
  "Real World Assets",
  "Moonshot",
  "Polkadot Ecosystem",
  "Research",
  "Algorithmic Stablecoin",
  "Liquid Staking Derivatives",
  "Toncoin Ecosystem",
  "Ethereum Ecosystem",
  "Circle Ventures Portfolio",
  "Blockchain Capital Portfolio",
  "Cardano Ecosystem",
  "Smart Contracts",
  "Tokenized Gold",
  "Gaming",
  "Entertainment",
  "Derivatives",
  "Framework Ventures Portfolio",
  "AI Memes",
  "MetisDAO Ecosystem",
  "Rollups-as-a-Service",
  "Coinfund Portfolio",
  "DeSci",
  "XDC Ecosystem",
  "Centralized Exchange Token",
  "Content Creation",
  "Celebrity Memes",
  "DCG Portfolio",
  "Zero Knowledge Proofs",
  "Tap To Earn",
  "Data Availability",
  "Video",
  "Tokenized commodities",
  "AI Agents",
  "SEI Ecosystem",
  "BRC-20",
  "Restaking",
  "Hyperliquid Ecosystem",
  "Scaling",
  "Account Abstraction",
  "Animal Memes",
  "Electric Global Portfolio",
  "PetRock Capital Portfolio",
  "DeFAI",
  "Optimism Ecosystem",
  "Metaverse",
  "Synthetics",
  "Runes",
  "Prediction Markets",
  "Sharing Economy",
  "Aptos Ecosystem",
  "SUI Ecosystem",
  "Blast Ecosystem",
  "Tezos Ecosystem",
  "Masternodes",
  "Modular Blockchain",
  "Avalanche Ecosystem"
];
